GAME_SIZE = (14, 14)
SNAKE1_INITIAL_HEAD = (6, 5)
SNAKE1_INITIAL_DIRECTION = (0, -1) # DOWN

SNAKE2_INITIAL_HEAD = (7, 8)
SNAKE2_INITIAL_DIRECTION = (0, 1) # UP

SNAKES_INITIAL_SIZE = 3

MAX_GAME_ITERATIONS = 500
